aemsites/infosys

styles/styles.css

Fix https://github.com/aemsites/infosys/issues/11
Test URLs:
Before: https://main--infosys--aemsites.hlx.live/iki
After: https://issue-11-v3--infosys--aemsites.hlx.live/iki

Added base box-sizing and font-size

---

styles/styles.css

Fix https://github.com/aemsites/infosys/issues/11
Test URLs:
Before: https://main--infosys--aemsites.hlx.live/iki
After: https://issue-11-v4--infosys--aemsites.hlx.live/iki

Added font size as defined in current iki.html

---

head.html
scripts/aem.js
styles/icons.css

Fix #11 
Test URLs:
Before: https://main--infosys--aemsites.hlx.live/iki
After: https://issue-11-v5--infosys--aemsites.hlx.live/iki

Added way to support icomoon icons

---

blocks/accordion/accordion.css
blocks/accordion/accordion.js
styles/styles.css

[Author doc](https://adobe.sharepoint.com/sites/HelixProjects/_layouts/15/doc.aspx?sourcedoc={554c3305-b2fb-4382-b113-22b84ad5f613}&action=edit)
Fix #4
Test URLs:
- Before: https://main--infosys--aemsites.hlx.live/drafts/anuj/accordion
- After: https://accordion--infosys--aemsites.hlx.live/drafts/anuj/accordion

Accordion Block

---

blocks/hero-slider/hero-slider.js
styles/styles.css

Fix #35
Test URLs:
- Before: https://main--infosys--aemsites.hlx.live/
- After: https://issue-35-v1--infosys--aemsites.hlx.live/drafts/shroti/iki

issue 35: fixed headings

---

blocks/cards-grid/cards-grid.css
blocks/cards-grid/cards-grid.js
styles/styles.css

Fix #6
Test URLs:
- Before: https://main--infosys--aemsites.hlx.live/drafts/anuj/cards-grid
- After: https://featured--infosys--aemsites.hlx.live/drafts/anuj/cards-grid

cards-grid block implementation

---

blocks/hero-slider/hero-slider.css
blocks/subscription/subscription.css
blocks/subscription/subscription.js

Resolved lint issues and got rid of un-neccessary loops as well.
Fix #<gh-issue-id>
Test URLs:
- After: https://lint-issue--infosys--aemsites.hlx.page/iki

fix: resolved lint issues

---

blocks/header/header.css
blocks/modal/modal.js
blocks/search/search.css
blocks/search/search.js
styles/icons.css
styles/styles.css

Fix #8 
1. Implemented a modal for search.
2. Integrated Search & Suggestions API.
3. Rendered search results and suggestions.
4. Added animations for UI elements.
5. Optimized for desktop, mobile, and tablet.
6. Ensured responsiveness across all devices.
Test URLs:
- Before: https://main--infosys--aemsites.hlx.live/drafts/shroti/header
- After: https://issue-1-v4--infosys--aemsites.hlx.live/drafts/shroti/header

Issue 8 : Add Support for Search Functionality

---

blocks/header/header.css
blocks/header/header.js
blocks/social-wrapper/social-wrapper.css

Fix #1
Fixed remaining Header part - Hamburger Menu (Mobile View)
Test URLs:
- Before: https://main--infosys--aemsites.hlx.live/drafts/shroti/header
- After: https://issue-1-v6--infosys--aemsites.hlx.live/drafts/shroti/header

Issue 1 : Header - Hamburger Menu (Mobile Menu)

---

scripts/aem.js
scripts/delayed.js

Added One Trust SDK Consent support 
Fix #22
Test URLs:
- After: https://issue-22-v1--infosys--aemsites.hlx.live/iki

Issue 22: consent support

---

scripts/scripts.js
styles/icons.css
styles/styles.css

Added Scroll to Top button (i.e. Navigation Block)
Fix #7 
Test URLs:
- After: https://issue-7-v1--infosys--aemsites.hlx.live/iki

Issue 7: Added Scroll to Top button (i.e. Navigation Block)

---

scripts/aem.js
styles/styles.css

Fix #22 
As part of this PR, fixed two trivial issues:
1. One of the OneTrustSDK <script> tags was not getting created properly - fixed
3. ScrollToTop was appearing on Page Load - Fixed
Test URLs:
- After: https://issue-22-v2--infosys--aemsites.hlx.live/iki

Fixed consent Script tag creation

---

blocks/accordion/accordion.css
blocks/cards-grid/cards-grid.css
blocks/carousel/carousel.css
blocks/filters-grid/filters-grid.css

Fix #59 
Test URLs:
- After: https://issue-59--infosys--aemsites.hlx.live/iki

fixing blocks styling issues

---

blocks/carousel/carousel.css
blocks/carousel/carousel.js

Fix #<gh-issue-id>
Test URLs:
- After: https://carousel-1--infosys--aemsites.hlx.live/iki

fix: add parent selector for carousel css

---

blocks/hero-slider/hero-slider.css
blocks/hero-slider/hero-slider.js
scripts/blocks-utils.js

Fix #<gh-issue-id>
Test URLs:
- Before: https://main--infosys--aemsites.hlx.live/
- After: https://<branch>--infosys--aemsites.hlx.live/

Hero slider background image optimisation

---

blocks/accordion/accordion.js
blocks/hero-slider/hero-slider.css
blocks/hero-slider/hero-slider.js
scripts/blocks-utils.js

Updated two blocks - 
1. Hero-Slider: Changed DOM Structure and logic to show background. Earlier background img src was explicitly set via js on block's parent DIV. Now, banner-imgs have been moved under the parent DIV occupying 100% width and their visibility is controlled via '.active' class.
2. Accordion Block: The background img of collapsed item is set using new method getOptimalImageFromPictureTag() which takes picture element as input and returns the web optimal img src by matching the media.
Fix #62 
Test URLs:
- After: https://issue-62--infosys--aemsites.hlx.live/iki

Setting optimised background image src

---

blocks/filters-grid/filters-grid.js
blocks/hero-slider/hero-slider.js
scripts/blocks-utils.js

Introduced `getPlaceHolders(inpPlaceholders)` which updates the inpPlaceholders object keys with actual value from the excel sheet.
Fix #29 
Test URLs:
- After: https://issue-29--infosys--aemsites.hlx.live/iki

Replace hard coded strings with the placeholders

---

blocks/subscription/subscription.css
blocks/subscription/subscription.js

Recording of animation added -
https://github.com/aemsites/infosys/assets/66720268/71c9cda8-aaa6-4723-907d-41b0f75fc9bd
Fix #41 
Test URLs:
- After: https://issue-41--infosys--aemsites.hlx.live/iki

adding subscription block open animation

---

blocks/footer/footer.js
blocks/header/header.js
blocks/hero-slider/hero-slider.js
blocks/subscription/subscription.js

Fixed two seo issues -
1. Added href='#' in empty <a> tags - one in subscription block and other in footer block
2. Made 3 links descriptive in hero slider block
SEO Score improved from 54 to 86.
The only issue left is page is not indexed, which I think is fine until page is made live.
Accessibility score improved from 95 to 98 by adding aria-label to search icon header.
Fix #70 
Test URLs:
- After: https://issue-70--infosys--aemsites.hlx.live/iki

Improve SEO and Accessibility Score

---

blocks/advanced-heading/advanced-heading.css
blocks/cards-grid/cards-grid.css
blocks/filters-grid/filters-grid.css
blocks/hero-slider/hero-slider.css
blocks/hero-slider/hero-slider.js
styles/styles.css

Fix #76 
Test URLs:
- After: https://issue-76--infosys--aemsites.hlx.live/iki

Improving hero slider, featured and filters-grid block

---

blocks/footer/footer.css
blocks/footer/footer.js

Fix #79
Test URLs:
- After: https://issue-79--infosys--aemsites.hlx.live/iki

fix: footer issues

---

blocks/subscription/subscription.css

Fix #84 
Test URLs:
- After: https://issue-84--infosys--aemsites.hlx.live/iki

fix: adjust block height and fix media queries

---

blocks/subscription/subscription.js
scripts/delayed.js

Fix #81 
Test URLs:
- After: https://marcom-form--infosys--aemsites.hlx.live/iki

fix: support marcom form submission

---

blocks/carousel/carousel.css
blocks/carousel/carousel.js

Fix #89
Test URLs:
- After: https://issue-89--infosys--aemsites.hlx.live/iki

fix: most popular section UAT issues

---

blocks/hero-slider/hero-slider.css
blocks/hero-slider/hero-slider.js

Improvements/Bugs -
1. While changing the banner image in hero slider, it should transition smoothly.
2. In mobile view, while transitioning box shadow should not be visible
3. (Bug) If active card item is clicked, the card hides
4. Card items movement should be cyclic
Fix #86 
Test URLs:
- After: https://issue-86--infosys--aemsites.hlx.live/iki

UAT: hero slider fixes

---

blocks/accordion/accordion.css
blocks/accordion/accordion.js

1. Removed animation while opening the accordion block item
2. Set item width = 8rem
Fix #87 
Test URLs:
- After: https://issue-87--infosys--aemsites.hlx.live/iki

[UAT] Our Radar Block Improvement

---

blocks/header/header.css

Fix #74
Test URLs:
- After: https://issue-74-v3--infosys--aemsites.hlx.live/iki

restored header's font size

---

blocks/header/header.css

Fix #74
Test URLs:
- After: https://issue-74-v4--infosys--aemsites.hlx.live/iki

fixed font for the mobile view

---

blocks/subscription/subscription.js
scripts/aem.js

Fix #88 
Test URLs:
- After: https://issue-88-v2--infosys--aemsites.hlx.live/iki

Issue 88: Fixed Alt Text for the Image tags for icons

---

blocks/social-wrapper/social-wrapper.js
styles/icons.css

Fix #101 
Test URLs:
- Before: https://main--infosys--aemsites.hlx.live/
- After: https://issue-101--infosys--aemsites.hlx.live/

fix: icon handling in social wrapper

---

blocks/accordion/accordion.css
blocks/accordion/accordion.js

Accordion block refactored, DOM structure made similar to existing site and handled transitions similarly to ensure we get same effect.
Fix #103 
Test URLs:
- After: https://issue-103--infosys--aemsites.hlx.live/iki

Accordion block refactored

---

blocks/hero-slider/hero-slider.css
blocks/hero-slider/hero-slider.js

1. Refactored hero slider block implementation, simplified block logic and specifically progress bar implementation
2. Banner & Slide Transition improved
3. Font sizes re-matched
4. Handled banner heading wrap
Fix #107 
Test URLs:
- After: https://issue-107--infosys--aemsites.hlx.live/iki

fix: hero slider refactored

---

blocks/hero-slider/hero-slider.css
blocks/hero-slider/hero-slider.js

Fix #109 
Test URLs:
- After: https://issue-109--infosys--aemsites.hlx.live/iki

fix: hero slider touch event handling and general styling

---

blocks/cards-grid/cards-grid.css

Fix #114 
Test URLs:
- After: https://issue-114--infosys--aemsites.hlx.live/iki

fix: cards grid block font sizes and show ellipses for large text

---

blocks/cards-grid/cards-grid.css
blocks/header/header.css
blocks/hero-slider/hero-slider.css
scripts/scripts.js
styles/styles.css

- Header font size
- Header logo alignment
- Header sign in color
- Hero slider block > report button font size
- Cards grid block > find more button font size
- scroll to top button size
Fix #106 
Test URLs:
- After: https://issue-106--infosys--aemsites.hlx.live/iki

Page appears zoomed

---

blocks/carousel/carousel.css
blocks/header/header.css
blocks/hero-slider/hero-slider.css
blocks/hero-slider/hero-slider.js
blocks/search/search.css
scripts/scripts.js
styles/styles.css

Fix #121 #122 #123 #124 #125 #126 #128 #129 
Test URLs:
- After: https://uat--infosys--aemsites.hlx.live/iki

fix: uat issues

---

blocks/carousel/carousel.js

Fix #127 
Test URLs:
- After: https://issue-127--infosys--aemsites.hlx.live/iki

fix: cyclic carousel
